-- ============================================================
-- UZEE TECH ScreenGuard Finder — Display Size Update
-- Source: UZEE_TECH_SUPER_D_MASTER_263_WITH_DISPLAY_SIZE_QA.xlsx (sheet: MASTER_263)
-- Generated by diffing the workbook against the current dataset.
--
-- SCOPE OF THIS UPDATE (verified diff — see report):
--   - Group IDs:        0 added, 0 removed (263 = 263, unchanged)
--   - Compatible Models: 0 changes (unchanged)
--   - Box Number:        NOT touched (preserves whatever is live/editable in Supabase)
--   - Title/Source/Verification/Notes: 0 changes (unchanged)
--   - Display Size:      70 groups updated from "Unknown" -> a sourced value
--                         0 regressions (no group goes from a known size back to Unknown)
--
-- This script ONLY updates the display_size column for 70 specific Group IDs.
-- It does not touch box_number, models, title, source, verification, notes, or category.
-- Wrapped in a transaction so it is fully atomic: all 70 rows update or none do.
-- ============================================================

BEGIN;

UPDATE boxes SET display_size = '4.7"' WHERE id = 'SD-F001' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '5.5"' WHERE id = 'SD-F003' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.5"' WHERE id = 'SD-F004' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '4.7"' WHERE id = 'SD-F005' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '5.5"' WHERE id = 'SD-F006' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '5.8"' WHERE id = 'SD-F007' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.1"' WHERE id = 'SD-F009' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.5"' WHERE id = 'SD-F011' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.1"' WHERE id = 'SD-F015' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.7"' WHERE id = 'SD-F017' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.1"' WHERE id = 'SD-F021' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.7"' WHERE id = 'SD-F023' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.1"' WHERE id = 'SD-F025' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.7"' WHERE id = 'SD-F027' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.1"' WHERE id = 'SD-F029' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.7"' WHERE id = 'SD-F031' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.3"' WHERE id = 'SD-F037' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.88"' WHERE id = 'SD-F047' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.53"' WHERE id = 'SD-F048' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.88"' WHERE id = 'SD-F049' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.7"' WHERE id = 'SD-F050' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.88"' WHERE id = 'SD-F051' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.67"' WHERE id = 'SD-F052' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.88"' WHERE id = 'SD-F053' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.2"' WHERE id = 'SD-F054' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.88"' WHERE id = 'SD-F055' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.53"' WHERE id = 'SD-F056' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.71"' WHERE id = 'SD-F057' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.5"' WHERE id = 'SD-F058' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.5"' WHERE id = 'SD-F059' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.79"' WHERE id = 'SD-F062' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.88"' WHERE id = 'SD-F065' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.67"' WHERE id = 'SD-F068' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.67"' WHERE id = 'SD-F072' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.43"' WHERE id = 'SD-F074' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.67"' WHERE id = 'SD-F077' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.6"' WHERE id = 'SD-F080' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.6"' WHERE id = 'SD-F081' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.4"' WHERE id = 'SD-F082' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.67"' WHERE id = 'SD-F083' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.67"' WHERE id = 'SD-F084' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.7"' WHERE id = 'SD-F085' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.26"' WHERE id = 'SD-F086' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.78"' WHERE id = 'SD-F087' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.3"' WHERE id = 'SD-F088' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.59"' WHERE id = 'SD-F089' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.58"' WHERE id = 'SD-F090' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.7"' WHERE id = 'SD-F091' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.7"' WHERE id = 'SD-F092' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.73"' WHERE id = 'SD-F093' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.78"' WHERE id = 'SD-F094' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.7"' WHERE id = 'SD-F095' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.67"' WHERE id = 'SD-F096' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.67"' WHERE id = 'SD-F097' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.67"' WHERE id = 'SD-F098' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.67"' WHERE id = 'SD-F121' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.7"' WHERE id = 'SD-F128' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.51"' WHERE id = 'SD-F143' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.78"' WHERE id = 'SD-F205' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.1"' WHERE id = 'SD-F208' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.9"' WHERE id = 'SD-F209' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.3"' WHERE id = 'SD-F210' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.9"' WHERE id = 'SD-F211' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.3"' WHERE id = 'SD-F212' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.9"' WHERE id = 'SD-F213' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.78"' WHERE id = 'SD-F218' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.53"' WHERE id = 'SD-F220' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.88"' WHERE id = 'SD-F223' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.88"' WHERE id = 'SD-F224' AND display_size = 'Unknown';
UPDATE boxes SET display_size = '6.88"' WHERE id = 'SD-F225' AND display_size = 'Unknown';

-- Verification query — expect exactly 70 rows with display_size <> 'Unknown' among these IDs,
-- and total group/relationship counts unchanged (263 / 1617).
SELECT
  (SELECT COUNT(*) FROM boxes) AS total_groups,
  (SELECT COUNT(*) FROM models) AS total_relationships,
  (SELECT COUNT(*) FROM boxes WHERE display_size <> 'Unknown') AS groups_with_display_size;

COMMIT;
